-- 011_search_plans.sql
--
-- Stores versioned, immutable Search Plans generated by the Search Planner.
--
-- Design notes (FINAL_ARCHITECTURE.md § 16 "Search Query Planner"):
--   - "The plan itself is a versioned, inspectable artifact."
--   - Plans are IMMUTABLE after creation.  plan_json is NEVER updated.
--     If the Candidate Intelligence Profile changes, a new plan row is inserted
--     with an incremented plan_version.  Version 1 is never modified.
--   - This design makes regression detection possible: a plan for a given
--     profile_version can be regenerated and diffed without losing historical data.
--   - execution_runs.search_plan_id always references the exact plan version
--     that produced those results, enabling deterministic replay.
--   - NO updated_at column — the absence is intentional and documents the
--     immutability guarantee.  The migration runner's updated_at trigger
--     (migration 008) is not applied here.
--   - status ('active' | 'superseded') is metadata for the consumer, not an
--     indicator that plan_json was changed.  When a new plan version is
--     generated, the prior row is updated ONLY in its status field, never
--     in plan_json or any other content column.

BEGIN;

CREATE TABLE IF NOT EXISTS search_plans (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id     UUID         NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  profile_version  TEXT         NOT NULL,
  plan_version     TEXT         NOT NULL DEFAULT '1.0.0',
  plan_json        JSONB        NOT NULL,
  query_count      INTEGER      NOT NULL DEFAULT 0
                   CHECK (query_count >= 0),
  status           TEXT         NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'superseded')),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
  -- Intentionally no updated_at: plans are immutable after creation.
);

-- Fast lookup: latest plan for a given candidate.
CREATE INDEX IF NOT EXISTS idx_search_plans_candidate_id
  ON search_plans (candidate_id, created_at DESC);

-- Allow filtering by profile version for reproducibility audits.
CREATE INDEX IF NOT EXISTS idx_search_plans_profile_version
  ON search_plans (profile_version);

-- Status filter: list active plans without full scan.
CREATE INDEX IF NOT EXISTS idx_search_plans_active
  ON search_plans (candidate_id)
  WHERE status = 'active';

COMMIT;
